"""Emit the report's data tables straight from the live analyzer.

The previous design document drifted from the code: it still documented a five-terminal
grammar whose FIRST/FIRST conflict had long since been factored away. Everything the
rubric asks to see -- token tables, regular expressions, grammar rules, the transformation
ledger, FIRST/FOLLOW, the LL(1) table, accept/reject verdicts -- is therefore generated
here into generated/*.tex and \\input by the report, so it cannot go stale.

    python tools/export_tables.py
"""

from __future__ import annotations

import argparse
import os
import sys
from collections import Counter
from pathlib import Path

from yaounde_analyzer.core import text as text_module
from yaounde_analyzer.core.analysis import (
    TOPIC_KEYWORDS,
    PreparedAnalyzer,
    analyze_tokens_and_parse,
    compute_statistics,
)
from yaounde_analyzer.core.corpus import validate_import
from yaounde_analyzer.core.lexicon import EntrySource
from yaounde_analyzer.core.specs import (
    load_demo_corpus_records,
    load_demo_grammar,
    load_demo_lexicon,
)

OUT = Path(__file__).resolve().parent.parent / "generated"
EOF = r"\$"

_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def tex(value: object) -> str:
    return "".join(_ESCAPES.get(ch, ch) for ch in str(value))


def write(name: str, body: str) -> None:
    (OUT / name).write_text(body.rstrip() + "\n", encoding="utf-8")
    print(f"  generated/{name}")


def facts(analyzer: PreparedAnalyzer, records: list[dict]) -> None:
    lexicon, grammar = analyzer.lexicon, analyzer.descriptive_grammar
    by_source = Counter(str(e.source) for e in lexicon.entries)
    accepted = sum(
        analyze_tokens_and_parse(r["raw_text"], analyzer)[1].accepted for r in records
    )
    values = {
        "LexiconTotal": len(lexicon.entries),
        "LexiconCorpus": by_source.get("corpus", 0),
        "LexiconDictionary": by_source.get("dictionary", 0),
        "LexiconMultiword": sum(1 for e in lexicon.entries if len(e.words) > 1),
        "TerminalCount": len(grammar.terminals),
        "NonterminalCount": len(grammar.nonterminals),
        "ProductionCount": len(grammar.productions),
        "ExecProductionCount": len(analyzer.grammar.productions),
        "LedgerSteps": len(analyzer.transformation_steps),
        "CorpusTotal": len(records),
        "CorpusAccepted": accepted,
        "CorpusRejected": len(records) - accepted,
        "CorpusAttested": sum(
            1 for r in records
            if r["source_kind"] == "field" and r["manual_transcription_attested"]
        ),
        "TopicCount": len(TOPIC_KEYWORDS),
        "OriginCount": len({str(c) for e in lexicon.entries for c in e.language_candidates}),
        "GrammarVersion": tex(grammar.version),
        "LexiconVersion": tex(lexicon.version),
    }
    lines = [r"% Generated by tools/export_tables.py -- do not edit."]
    lines += [rf"\newcommand{{\{k}}}{{{v}}}" for k, v in values.items()]
    write("facts.tex", "\n".join(lines))


def regex_table() -> None:
    rows = [
        ("WORD", text_module._WORD_RE.pattern,
         "Letters and combining accents, with internal apostrophes or hyphens"),
        ("NUMBER", text_module._NUMBER_RE.pattern, "A run of digits"),
        ("SPACE", text_module._SPACE_RE.pattern, "Horizontal whitespace only"),
        ("NEWLINE", text_module._NEWLINE_RE.pattern, "One or more line breaks"),
        ("PUNCTUATION", text_module._PUNCTUATION_RE.pattern,
         "Sentence and clause marks, including guillemets"),
    ]
    body = [
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Regular expressions driving the scanner, exported from \texttt{core/text.py}.}",
        r"\label{tab:regex}",
        r"\begin{tabular}{@{}l p{0.40\linewidth} p{0.32\linewidth}@{}}",
        r"\toprule",
        r"\textbf{Span kind} & \textbf{Regular expression} & \textbf{Matches} \\",
        r"\midrule",
    ]
    for kind, pattern, meaning in rows:
        # Allow a line break after every character: regexes have no natural
        # break points and would otherwise overflow the column.
        breakable = r"\allowbreak{}".join(tex(ch) for ch in pattern)
        body.append(rf"\texttt{{{kind}}} & \ttfamily\scriptsize {breakable} & {meaning} \\")
        body.append(r"\addlinespace")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    write("regexes.tex", "\n".join(body))


# Student numbers are the collector ids; names are for the report only.
TEAM = {
    "ICTU20241386": "Kamdeu Yamdjeuson Neil Marshall",
    "ICTU20241297": "Eyong Seanna Tabe",
    "ICTU20241393": "Tuheu Tchoubi Pempeme Moussa Fahdil",
}


def collectors(analyzer: PreparedAnalyzer, records: list[dict]) -> None:
    by_collector = Counter(str(r["collector_id"]) for r in records)
    accepted = Counter(
        str(r["collector_id"]) for r in records
        if analyze_tokens_and_parse(r["raw_text"], analyzer)[1].accepted
    )
    body = [
        r"\begin{tabular}{@{}llrr@{}}",
        r"\toprule",
        r"\textbf{Collector} & \textbf{Id} & \textbf{Statements} & \textbf{Accepted} \\",
        r"\midrule",
    ]
    for collector_id, count in sorted(by_collector.items()):
        name = TEAM.get(collector_id, "--")
        body.append(
            rf"{tex(name)} & \texttt{{{tex(collector_id)}}} & {count} & "
            rf"{accepted.get(collector_id, 0)} \\"
        )
    body += [
        r"\midrule",
        rf"\textbf{{Total}} & & \textbf{{{len(records)}}} & "
        rf"\textbf{{{sum(accepted.values())}}} \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    write("collectors.tex", "\n".join(body))


def lexicon_summary(analyzer: PreparedAnalyzer) -> None:
    entries = analyzer.lexicon.entries
    by_terminal = Counter(e.terminal for e in entries)
    slang = Counter(e.terminal for e in entries if e.is_slang)
    body = [
        r"\begin{tabular}{@{}lrrl@{}}",
        r"\toprule",
        r"\textbf{Terminal} & \textbf{Entries} & \textbf{Slang} & \textbf{Example} \\",
        r"\midrule",
    ]
    for terminal, count in sorted(by_terminal.items(), key=lambda kv: -kv[1]):
        example = next(e.canonical for e in entries if e.terminal == terminal)
        body.append(
            rf"{terminal} & {count} & {slang.get(terminal, 0)} & \texttt{{{tex(example)}}} \\"
        )
    body += [
        r"\midrule",
        rf"\textbf{{Total}} & \textbf{{{len(entries)}}} & \textbf{{{sum(slang.values())}}} & \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    write("lexicon-summary.tex", "\n".join(body))

    origins = Counter(str(c) for e in entries for c in e.language_candidates)
    rows = [
        rf"{tex(name)} & {count} \\"
        for name, count in sorted(origins.items(), key=lambda kv: -kv[1])
    ]
    write(
        "origin-summary.tex",
        "\n".join(
            [r"\begin{tabular}{@{}lr@{}}", r"\toprule",
             r"\textbf{Donor language} & \textbf{Token entries} \\", r"\midrule",
             *rows, r"\bottomrule", r"\end{tabular}"]
        ),
    )


def lexicon_sample(analyzer: PreparedAnalyzer) -> None:
    """A readable slice: the corpus-attested entries, which are the graded evidence."""
    entries = [e for e in analyzer.lexicon.entries if e.source is EntrySource.CORPUS]
    head = (
        r"\textbf{Canonical} & \textbf{Terminal} & \textbf{POS} & \textbf{Origin} & "
        r"\textbf{Attested in} \\"
    )
    body = [
        r"\begin{longtable}{@{}llll p{0.30\linewidth}@{}}",
        r"\toprule",
        head,
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        head,
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]
    for entry in entries:
        origin = ", ".join(str(c) for c in entry.language_candidates)
        evidence = ", ".join(entry.evidence_statement_ids[:3])
        if len(entry.evidence_statement_ids) > 3:
            evidence += r", \ldots"
        body.append(
            rf"\texttt{{{tex(entry.canonical)}}} & {tex(entry.terminal)} & "
            rf"{tex(entry.part_of_speech)} & {tex(origin)} & \small {tex(evidence)} \\"
        )
    body.append(r"\end{longtable}")
    write("lexicon-corpus.tex", "\n".join(body))


def grammar_rules(analyzer: PreparedAnalyzer) -> None:
    for name, grammar in (
        ("grammar-original.tex", analyzer.descriptive_grammar),
        ("grammar-transformed.tex", analyzer.grammar),
    ):
        grouped: dict[str, list] = {}
        for production in grammar.productions:
            grouped.setdefault(production.lhs, []).append(production)
        body = [r"\begin{longtable}{@{}l l l@{}}", r"\toprule",
                r"\textbf{Nonterminal} & \textbf{Production} & \textbf{Rule id} \\",
                r"\midrule", r"\endhead", r"\bottomrule", r"\endfoot"]
        for lhs, productions in grouped.items():
            for index, production in enumerate(productions):
                if production.rhs:
                    rhs = rf"\texttt{{{tex(' '.join(production.rhs))}}}"
                else:
                    rhs = r"$\varepsilon$"
                arrow = r"$\rightarrow$" if index == 0 else r"$\mid$"
                head = tex(lhs) if index == 0 else ""
                body.append(
                    rf"\texttt{{{head}}} & {arrow} {rhs} & "
                    rf"\scriptsize\texttt{{{tex(production.id)}}} \\"
                )
            body.append(r"\addlinespace")
        body.append(r"\end{longtable}")
        write(name, "\n".join(body))


def ledger(analyzer: PreparedAnalyzer) -> None:
    body = [r"\begin{longtable}{@{}p{0.20\linewidth}p{0.46\linewidth}p{0.26\linewidth}@{}}",
            r"\toprule",
            r"\textbf{Transformation} & \textbf{Description} & \textbf{Rules produced} \\",
            r"\midrule", r"\endhead", r"\bottomrule", r"\endfoot"]
    for step in analyzer.transformation_steps:
        produced = ", ".join(step.result_production_ids)
        body.append(
            rf"{tex(str(step.kind).replace('_', ' '))} & {tex(step.description)} & "
            rf"\scriptsize\texttt{{{tex(produced)}}} \\"
        )
        body.append(r"\addlinespace")
    body.append(r"\end{longtable}")
    write("ledger.tex", "\n".join(body))


def first_follow(analyzer: PreparedAnalyzer) -> None:
    first, follow = analyzer.first, analyzer.follow
    body = [r"\begin{longtable}{@{}l p{0.38\linewidth} p{0.38\linewidth}@{}}", r"\toprule",
            r"\textbf{Symbol} & \textbf{FIRST} & \textbf{FOLLOW} \\", r"\midrule",
            r"\endhead", r"\bottomrule", r"\endfoot"]
    for symbol in analyzer.grammar.nonterminals:
        f = ", ".join(sorted(first.get(symbol, frozenset()))) or "--"
        g = ", ".join(
            t if t != "$" else EOF for t in sorted(follow.get(symbol, frozenset()))
        ) or "--"
        body.append(rf"\texttt{{{tex(symbol)}}} & \small {tex(f)} & \small {tex(g)} \\")
    body.append(r"\end{longtable}")
    write("first-follow.tex", "\n".join(body))


def ll1_table(analyzer: PreparedAnalyzer) -> None:
    terminals = [*analyzer.grammar.terminals, "$"]
    cells = analyzer.table.entries
    header = " & ".join(
        rf"\rotatebox{{90}}{{\texttt{{{t if t != '$' else EOF}}}}}" for t in terminals
    )
    body = [
        rf"\begin{{longtable}}{{@{{}}l*{{{len(terminals)}}}{{c}}@{{}}}}",
        r"\toprule",
        rf"\textbf{{NT}} & {header} \\",
        r"\midrule", r"\endhead", r"\bottomrule", r"\endfoot",
    ]
    for nonterminal in analyzer.grammar.nonterminals:
        row = []
        for terminal in terminals:
            production_id = cells.get((nonterminal, terminal))
            cell = rf"\tiny\texttt{{{tex(production_id.split('.')[-1])}}}" if production_id else ""
            row.append(cell)
        body.append(rf"\texttt{{{tex(nonterminal)}}} & " + " & ".join(row) + r" \\")
    body.append(r"\end{longtable}")
    write("ll1-table.tex", "\n".join(body))


def corpus_results(analyzer: PreparedAnalyzer, records: list[dict]) -> None:
    body = [r"\begin{longtable}{@{}l p{0.40\linewidth} c c p{0.20\linewidth}@{}}", r"\toprule",
            r"\textbf{Id} & \textbf{Statement} & \textbf{Source} & \textbf{Verdict} & "
            r"\textbf{Reason} \\",
            r"\midrule", r"\endhead", r"\bottomrule", r"\endfoot"]
    for record in records:
        _, parse, _ = analyze_tokens_and_parse(record["raw_text"], analyzer)
        verdict = r"\accepted" if parse.accepted else r"\rejected"
        reason = "--" if parse.accepted else str(parse.rejection_reason).replace("_", " ")
        # A field record without manual attestation does not satisfy the marking scheme.
        source = str(record["source_kind"])
        if source == "field" and not record["manual_transcription_attested"]:
            source += r"\textsuperscript{*}"
        body.append(
            rf"\texttt{{{tex(record['statement_id'])}}} & \small {tex(record['raw_text'])} & "
            rf"\small {source} & {verdict} & \small {tex(reason)} \\"
        )
    body.append(r"\end{longtable}")
    write("corpus-results.tex", "\n".join(body))


def frequencies(analyzer: PreparedAnalyzer, records: list[dict]) -> None:
    from yaounde_analyzer.core.analysis import analyze_corpus

    stats = compute_statistics(analyze_corpus(validate_import(records), analyzer))
    def block(counter, caption_key: str, limit: int = 20) -> str:
        rows = sorted(counter.items(), key=lambda kv: (-kv[1], kv[0]))[:limit]
        return "\n".join(
            [r"\begin{tabular}{@{}lr@{}}", r"\toprule",
             rf"\textbf{{{caption_key}}} & \textbf{{Count}} \\", r"\midrule",
             *[rf"\texttt{{{tex(term)}}} & {count} \\" for term, count in rows],
             r"\bottomrule", r"\end{tabular}"]
        )
    write("freq-raw.tex", block(stats.raw_frequency, "Raw form"))
    write("freq-canonical.tex", block(stats.canonical_frequency, "Canonical form"))
    write("freq-terminal.tex", block(stats.terminal_frequency, "Terminal", limit=15))


def load_database_records(database_url: str) -> list[dict]:
    """Latest revision of every statement in a live corpus database."""
    from yaounde_analyzer.api.repository import list_statement_records, topics_from_json
    from yaounde_analyzer.storage.db import Database

    database = Database.create(database_url)
    session = database.session_factory()
    try:
        records = []
        for record in list_statement_records(session):
            latest = record.revisions[-1]
            records.append(
                {
                    "statement_id": record.statement_id,
                    "revision": latest.revision,
                    "raw_text": latest.raw_text,
                    "source_kind": latest.source_kind,
                    "manual_transcription_attested": latest.manual_transcription_attested,
                    "collector_id": latest.collector_id,
                    "topics": topics_from_json(latest.topics_json),
                    "created_at": latest.created_at.isoformat(),
                }
            )
        return sorted(records, key=lambda r: r["statement_id"])
    finally:
        session.close()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--database",
        default=os.environ.get("YAOUNDE_DATABASE_URL"),
        help="SQLAlchemy URL of a live corpus database. Defaults to $YAOUNDE_DATABASE_URL; "
             "falls back to the packaged field corpus when neither is set.",
    )
    parser.add_argument(
        "--field-only",
        action="store_true",
        help="Keep only manually attested field statements -- use this for the submitted report.",
    )
    args = parser.parse_args(argv)

    OUT.mkdir(exist_ok=True)
    analyzer = PreparedAnalyzer(load_demo_lexicon(), load_demo_grammar())
    analyzer.check()

    if args.database:
        records = load_database_records(args.database)
        origin = args.database
    else:
        records = load_demo_corpus_records()
        origin = "packaged field corpus"

    if args.field_only:
        records = [
            r for r in records
            if r["source_kind"] == "field" and r["manual_transcription_attested"]
        ]

    attested = sum(
        1 for r in records
        if r["source_kind"] == "field" and r["manual_transcription_attested"]
    )
    print(f"Exporting tables for {len(analyzer.lexicon.entries)} lexicon entries, "
          f"{len(records)} statements from {origin}")
    print(f"  attested field statements: {attested} / {len(records)}")
    facts(analyzer, records)
    regex_table()
    collectors(analyzer, records)
    lexicon_summary(analyzer)
    lexicon_sample(analyzer)
    grammar_rules(analyzer)
    ledger(analyzer)
    first_follow(analyzer)
    ll1_table(analyzer)
    corpus_results(analyzer, records)
    frequencies(analyzer, records)
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
